# Generated by Django 4.0 on 2024-09-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locality_name', models.CharField(max_length=100)),
                ('bhks', models.IntegerField()),
                ('per_sq_ft_area', models.IntegerField()),
                ('price_per_sq_ft_area', models.IntegerField()),
                ('construction_status', models.CharField(max_length=150)),
                ('price', models.BigIntegerField()),
                ('appt_name', models.TextField(max_length=200)),
                ('appt_link', models.URLField()),
            ],
        ),
    ]
